name: Docker build

on:
  push:
    branches: [ docker_build_fix ]
  pull_request:
    branches: [ docker_build_fix ]

# Unfortunately, we have to split these jobs since Github actions only has max 14GB storage
jobs:

  # Build and push the base image
  build-base-image:
    env:
      IMAGE_NAME: pccl/holodeck

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to DockerHub registry
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build base
      working-directory: ./docker
      run: docker build -t ${IMAGE_NAME}:base -f ./Dockerfile ..

    - name: Push base
      run: docker push ${IMAGE_NAME}:base
        
        
  
  # Build and push the default-worlds image
  build-default-worlds-image:
    env:
      IMAGE_NAME: pccl/holodeck

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Show disk availabilyt"
      run: df -Ph . | tail -1 | awk '{print $2 " " $4}'

    - name: Login to DockerHub registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build default-worlds
      working-directory: ./docker
      run: docker build -t ${IMAGE_NAME}:default-worlds -f ./Dockerfile_default_worlds ..

    - name: Push default-worlds
      run: docker push ${IMAGE_NAME}:default-worlds


  # Build and push the dexterity image
  build-dexterity-image:
    env:
      IMAGE_NAME: pccl/holodeck

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build dexterity
      working-directory: ./docker
      run: docker build -t ${IMAGE_NAME}:dexterity -f ./Dockerfile_dexterity ..

    - name: Push dexterity
      run: docker push ${IMAGE_NAME}:dexterity
